version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: bookinfo-redis
    ports:
      - "6379:6379"
    volumes:
      - bookinfo-redisdata:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mongo:
    build:
      context: .
      dockerfile: ./mongo-init/dockerfile
    container_name: bookinfo-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
    - bookinfo-mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: ratingDB    
  mongo-express:
    image: mongo-express
    container_name: bookinfo-mexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - bookinfo-postgresdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes: 
  bookinfo-mongodata:
  bookinfo-redisdata:
  bookinfo-postgresdata: