version: '3'
services:
  product-page:
    build: ../BookInfo.ProductPage/.
    container_name: bookinfo_productpage
    ports:
      - "5100:5100"
    environment: 
      BASE_URL : "http://+:5100"
      REVIEW_URL : "http://reviews:5111"
      DETAIL_URL : "http://details:5113"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookinfo-productpage
  ratings:
    build: ../BookInfo.Ratings/.
    container_name: bookinfo_ratings
    ports:
      - "5112:5112"
    environment: 
      BASE_URL : ":5112"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookinfo-ratings
  details:
    build: ../BookInfo.Details/.
    container_name: bookinfo_details
    ports:
      - "5113:5113"
    environment: 
      BASE_URL : ":5113"
      STOCK_URL : "http://stocks:5114"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookinfo-details
  reviews:
    build: ../BookInfo.Reviews/.
    container_name: bookinfo_reviews
    ports:
      - "5111:5111"
    environment: 
      BASE_URL : "http://+:5111"
      RATING_URL : "http://ratings:5112"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookinfo-reviews
  stocks:
    build: ../BookInfo.Stock/.
    container_name: bookinfo_stock
    ports:
      - "5114:5114"
    environment: 
      BASE_URL : "http://+:5114"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      JAEGER_SERVICE_NAME: bookinfo-stock
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bookinfo_jaeger
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  redis:
    image: bitnami/redis:latest
    container_name: bookinfo-redis
    ports:
      - "6379:6379"
    volumes:
      - /redis-persistence:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mongo:
    image: bookinfo-mongo
    container_name: bookinfo-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
    - bookinfo-mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: ratingDB    
  mongo-express:
    image: mongo-express
    container_name: bookinfo-mexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
volumes: 
  bookinfo-mongodata: