kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongoexpress
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongoexpress
    spec:
      containers:
        - name: mongoexpress
          image: mongo-express:latest
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: adminpass
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb.bookinfo.svc.cluster.local
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always