kind: Deployment
apiVersion: apps/v1
metadata:
  name: reviews
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 5m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5111
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 2
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          name: reviews
          livenessProbe:
            httpGet:
              path: /liveness
              port: 5111
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 2
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: BASE_URL
              value: 'http://*:5111'
            - name: RATING_URL
              value: ratings
            - name: ReviewConnStr
              value: >-
                Server=postgresql;Port=5432;Database=reviewdb;User
                Id=user;Password=pass
          ports:
            - containerPort: 5111
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: serdarkalayci/bookinfo-reviews:14
      restartPolicy: Always
 
 