kind: Deployment
apiVersion: apps/v1
metadata:
  name: stock
  namespace: bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5114
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 2
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          name: bookinfo-stock
          livenessProbe:
            httpGet:
              path: /liveness
              port: 5114
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 2
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: BASE_URL
              value: 'http://*:5114'
            - name: RedisAddress
              value: redis
            - name: DatabaseName
              value: '1'
          ports:
            - containerPort: 5114
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: serdarkalayci/bookinfo-stock:14
      restartPolicy: Always