kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: bookinfo
spec:
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    name: mongodb
  type: ClusterIP