kind: Service
apiVersion: v1
metadata:
  name: mongoexpress
  namespace: bookinfo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  selector:
    app: mongoexpress
  type: ClusterIP
 