kind: Service
apiVersion: v1
metadata:
  name: postgresql
  namespace: bookinfo
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgresql
  type: ClusterIP