apiVersion: v1
kind: Service
metadata:
  labels:
    app: productpage
  name: productpage
  namespace: bookinfo
spec:
  ports:
  - port: 5110
    protocol: TCP
    targetPort: 5110
  selector:
    app: productpage