apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings
  name: ratings
  namespace: bookinfo
spec:
  ports:
  - port: 5112
    protocol: TCP
    targetPort: 5112
  selector:
    app: ratings