kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: bookinfo
spec:
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    name: mongodb
  type: ClusterIP